language: node_js
sudo: false
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "iojs"
before_install:
  - npm install -g npm
env:
  - MULTIPLE_REDIS_TEST_USE_REDIS=true
services:
  - redis-server
