language: node_js
sudo: true
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "iojs"
before_install:
  - npm install -g npm
env: MULTIPLE_REDIS_TEST_USE_REDIS=true MULTIPLE_REDIS_TEST_INTEGRATION_HOST1=localhost MULTIPLE_REDIS_TEST_INTEGRATION_HOST2=otherhost MULTIPLE_REDIS_TEST_INTEGRATION_PORTS=7777,7778,6379 MULTIPLE_REDIS_TEST_INTEGRATION_KILL_PORT=7777 MULTIPLE_REDIS_TEST_INTEGRATION_PUB_SUB=false
services:
  - redis-server
before_script:
  - sudo redis-server /etc/redis/redis.conf --port 7777
  - sudo redis-server /etc/redis/redis.conf --port 7778
