language: node_js
sudo: true
node_js:
  - "node"
  - "8"
  - "6"
  - "4"
  - "0.12"
  - "0.10"
before_install:
  - npm install -g npm@^3
env:
  - MULTIPLE_REDIS_TEST_USE_REDIS=true
  - MULTIPLE_REDIS_TEST_INTEGRATION_HOST1=localhost
  - MULTIPLE_REDIS_TEST_INTEGRATION_HOST2=otherhost
  - MULTIPLE_REDIS_TEST_INTEGRATION_PORTS=7777,7778,6379
  - MULTIPLE_REDIS_TEST_INTEGRATION_CONF=/etc/redis/redis.conf
services:
  - redis-server
before_script:
  - chmod -R 777 ./test/helper/*.sh
  - sudo ./test/helper/start_redis.sh 7777 /etc/redis/redis.conf
  - sudo ./test/helper/start_redis.sh 7778 /etc/redis/redis.conf
