language: node_js
sudo: false
node_js:
  - "5.1"
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
  - "iojs"
before_install:
  - npm install -g npm
env:
  - MULTIPLE_REDIS_TEST_USE_REDIS=true
services:
  - redis-server
